// Code generated by MockGen. DO NOT EDIT.
// Source: plugin.go
//
// Generated by this command:
//
//	mockgen -source=plugin.go -package=plugin -destination=mock_plugin.go DevicePluginAPI
//
// Package plugin is a generated GoMock package.
package plugin

import (
	reflect "reflect"

	v1alpha1 "github.com/ROCm/gpu-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/apps/v1"
)

// MockDevicePluginAPI is a mock of DevicePluginAPI interface.
type MockDevicePluginAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDevicePluginAPIMockRecorder
}

// MockDevicePluginAPIMockRecorder is the mock recorder for MockDevicePluginAPI.
type MockDevicePluginAPIMockRecorder struct {
	mock *MockDevicePluginAPI
}

// NewMockDevicePluginAPI creates a new mock instance.
func NewMockDevicePluginAPI(ctrl *gomock.Controller) *MockDevicePluginAPI {
	mock := &MockDevicePluginAPI{ctrl: ctrl}
	mock.recorder = &MockDevicePluginAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicePluginAPI) EXPECT() *MockDevicePluginAPIMockRecorder {
	return m.recorder
}

// SetDRADriverAsDesired mocks base method.
func (m *MockDevicePluginAPI) SetDRADriverAsDesired(ds *v1.DaemonSet, devConfig *v1alpha1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDRADriverAsDesired", ds, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDRADriverAsDesired indicates an expected call of SetDRADriverAsDesired.
func (mr *MockDevicePluginAPIMockRecorder) SetDRADriverAsDesired(ds, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDRADriverAsDesired", reflect.TypeOf((*MockDevicePluginAPI)(nil).SetDRADriverAsDesired), ds, devConfig)
}

// SetDevicePluginAsDesired mocks base method.
func (m *MockDevicePluginAPI) SetDevicePluginAsDesired(ds *v1.DaemonSet, devConfig *v1alpha1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDevicePluginAsDesired", ds, devConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDevicePluginAsDesired indicates an expected call of SetDevicePluginAsDesired.
func (mr *MockDevicePluginAPIMockRecorder) SetDevicePluginAsDesired(ds, devConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDevicePluginAsDesired", reflect.TypeOf((*MockDevicePluginAPI)(nil).SetDevicePluginAsDesired), ds, devConfig)
}
