# NFD related configs
node-feature-discovery:
  # -- Set to true/false to enable/disable the installation of node feature discovery (NFD) operator
  enabled: true

# KMM related configs
kmm:
  # -- Set to true/false to enable/disable the installation of kernel module management (KMM) operator
  enabled: true
  controller:
    manager:
      env:
        # -- KMM kaniko builder image for building driver image within cluster
        relatedImageBuild: gcr.io/kaniko-project/executor:v1.23.2
        # -- KMM signer image for signing driver image's kernel module with given key pairs within cluster
        relatedImageSign: docker.io/rocm/kernel-module-management-signimage:v1.0.0
        # -- KMM worker image for loading / unloading driver kernel module on worker nodes
        relatedImageWorker: docker.io/rocm/kernel-module-management-worker:v1.0.0
        # -- Image pull secret name for pulling KMM kaniko builder image if registry needs credential to pull image
        relatedImageBuildPullSecret: ""
        # -- Image pull secret name for pulling KMM signer image if registry needs credential to pull image
        relatedImageSignPullSecret: ""
        # -- Image pull secret name for pulling KMM worker image if registry needs credential to pull image
        relatedImageWorkerPullSecret: ""
      image:
        # -- KMM controller manager image repository
        repository: docker.io/rocm/kernel-module-management-operator
        # -- KMM controller manager image tag
        tag: v1.0.0
      # -- Image pull policy for KMM controller manager pod
      imagePullPolicy: Always
      # -- Image pull secret name for pulling KMM controller manager image if registry needs credential to pull image
      imagePullSecrets: ""
    # -- Node selector for the KMM controller manager deployment
    nodeSelector: {}
    nodeAffinity:
      # -- Node affinity selector terms config for the KMM controller manager deployment, set it to [] if you want to make affinity config empty
      nodeSelectorTerms:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
  webhookServer:
    # -- KMM webhook's deployment node selector
    nodeSelector: {}
    nodeAffinity:
      # -- Node affinity selector terms config for the KMM webhook deployment, set it to [] if you want to make affinity config empty
      nodeSelectorTerms:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
    webhookServer:
      image:
        # -- KMM webhook image repository
        repository: docker.io/rocm/kernel-module-management-webhook-server
        # -- KMM webhook image tag
        tag: v1.0.0
      # -- Image pull policy for KMM webhook pod
      imagePullPolicy: Always
      # -- Image pull secret name for pulling KMM webhook image if registry needs credential to pull image
      imagePullSecrets: ""

# AMD GPU operator controller related configs
# -- Set to true to install default NFD rule for detecting AMD GPU hardware based on pci vendor ID and device ID
installdefaultNFDRule: true
controllerManager:
  manager:
    image:
      # -- AMD GPU operator controller manager image repository
      repository: docker.io/rocm/gpu-operator
      # -- AMD GPU operator controller manager image tag
      tag: v1.0.0
    # -- Image pull policy for AMD GPU operator controller manager pod
    imagePullPolicy: Always
    # -- Image pull secret name for pulling AMD GPU operator controller manager image if registry needs credential to pull image
    imagePullSecrets: ""
  # -- Node selector for AMD GPU operator controller manager deployment
  nodeSelector: {}
  nodeAffinity:
    # -- Node affinity selector terms config for the AMD GPU operator controller manager, set it to [] if you want to make affinity config empty
    nodeSelectorTerms:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
