controller:
  manager:
    args:
    - --config=controller_config.yaml
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      relatedImageMustGather: quay.io/edge-infrastructure/kernel-module-management-must-gather:release-2.1
      relatedImageSign: quay.io/edge-infrastructure/kernel-module-management-signimage:release-2.1
      relatedImageWorker: quay.io/edge-infrastructure/kernel-module-management-worker:release-2.1
      sslCertDir: /etc/pki/ca-trust/extracted/pem
    image:
      repository: quay.io/edge-infrastructure/kernel-module-management-operator
      tag: release-2.1
    imagePullPolicy: Always
    imagePullSecrets: ""
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    resources:
      limits:
        cpu: 500m
        memory: 384Mi
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  replicas: 1
  serviceAccount:
    annotations: {}
controllerManager:
  serviceAccount:
    annotations: {}
controllerMetricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
kmmDevicePlugin:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerConfigYaml: |-
    healthProbeBindAddress: :8081
    leaderElection:
      enabled: true
      resourceID: kmm.sigs.x-k8s.io
    webhook:
      disableHTTP2: true  # CVE-2023-44487
      port: 9443
    metrics:
      enableAuthnAuthz: true
      disableHTTP2: true  # CVE-2023-44487
      bindAddress: 0.0.0.0:8443
      secureServing: true
    worker:
      runAsUser: 0
      seLinuxType: spc_t
      setFirmwareClassPath: /var/lib/firmware
kmmModuleLoader:
  serviceAccount:
    annotations: {}
nodeLabeller:
  serviceAccount:
    annotations: {}
webhookServer:
  replicas: 1
  nodeSelector: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  webhookServer:
    args:
    - --config=controller_config.yaml
    - --enable-module
    - --enable-namespace
    - --enable-preflightvalidation
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: quay.io/edge-infrastructure/kernel-module-management-webhook-server
      tag: latest
    imagePullPolicy: Always
    imagePullSecrets: ""
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    resources:
      limits:
        cpu: 500m
        memory: 384Mi
      requests:
        cpu: 10m
        memory: 64Mi
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
