/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the \"License\");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an \"AS IS\" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: pod.go
//
// Generated by this command:
//
//	mockgen -source=pod.go -package=watchers -destination=mock_pod.go PodEventHandlerAPI
//
// Package watchers is a generated GoMock package.
package watchers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	workqueue "k8s.io/client-go/util/workqueue"
	event "sigs.k8s.io/controller-runtime/pkg/event"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// MockPodEventHandlerAPI is a mock of PodEventHandlerAPI interface.
type MockPodEventHandlerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPodEventHandlerAPIMockRecorder
}

// MockPodEventHandlerAPIMockRecorder is the mock recorder for MockPodEventHandlerAPI.
type MockPodEventHandlerAPIMockRecorder struct {
	mock *MockPodEventHandlerAPI
}

// NewMockPodEventHandlerAPI creates a new mock instance.
func NewMockPodEventHandlerAPI(ctrl *gomock.Controller) *MockPodEventHandlerAPI {
	mock := &MockPodEventHandlerAPI{ctrl: ctrl}
	mock.recorder = &MockPodEventHandlerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodEventHandlerAPI) EXPECT() *MockPodEventHandlerAPIMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPodEventHandlerAPI) Create(ctx context.Context, evt event.CreateEvent, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", ctx, evt, q)
}

// Create indicates an expected call of Create.
func (mr *MockPodEventHandlerAPIMockRecorder) Create(ctx, evt, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPodEventHandlerAPI)(nil).Create), ctx, evt, q)
}

// Delete mocks base method.
func (m *MockPodEventHandlerAPI) Delete(ctx context.Context, evt event.DeleteEvent, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", ctx, evt, q)
}

// Delete indicates an expected call of Delete.
func (mr *MockPodEventHandlerAPIMockRecorder) Delete(ctx, evt, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPodEventHandlerAPI)(nil).Delete), ctx, evt, q)
}

// Generic mocks base method.
func (m *MockPodEventHandlerAPI) Generic(ctx context.Context, evt event.GenericEvent, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Generic", ctx, evt, q)
}

// Generic indicates an expected call of Generic.
func (mr *MockPodEventHandlerAPIMockRecorder) Generic(ctx, evt, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generic", reflect.TypeOf((*MockPodEventHandlerAPI)(nil).Generic), ctx, evt, q)
}

// Update mocks base method.
func (m *MockPodEventHandlerAPI) Update(ctx context.Context, evt event.UpdateEvent, q workqueue.TypedRateLimitingInterface[reconcile.Request]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", ctx, evt, q)
}

// Update indicates an expected call of Update.
func (mr *MockPodEventHandlerAPIMockRecorder) Update(ctx, evt, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPodEventHandlerAPI)(nil).Update), ctx, evt, q)
}
