apiVersion: v1
kind: Pod
metadata:
  name: pytorch-gpu-pod
  labels:
    purpose: demo-pytorch-amdgpu
spec:
  containers:
    - name: pytorch-gpu-container
      image: rocm/pytorch:latest
      workingDir: /root
      command: ["/bin/bash", "-c", "--"]
      args: ["rocm-smi > /tmp/rocm-smi-output; git clone https://github.com/ROCm/pytorch-micro-benchmarking.git; cd pytorch-micro-benchmarking;  python micro_benchmarking_pytorch.py --network resnet50 --compile > /tmp/benchmark-output; sleep infinity & wait"]
      resources:
        limits:
          amd.com/gpu: 1 # requesting a GPU