apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kmm.fullname" . }}-cluster-ca
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
    config.openshift.io/inject-trusted-cabundle: "true"
    kmm.openshift.io/ca.type: cluster
  {{- include "kmm.labels" . | nindent 4 }}
data: {}