apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kmm.fullname" . }}-event-recorder-clusterrole
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
  {{- include "kmm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch