apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kmm.fullname" . }}-manager-config
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
  {{- include "kmm.labels" . | nindent 4 }}
data:
  controller_config.yaml: {{ .Values.managerConfig.controllerConfigYaml | toYaml
    | indent 1 }}