apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kmm.fullname" . }}-prometheus-k8s
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
  {{- include "kmm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kmm.fullname" . }}-prometheus-k8s
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
  {{- include "kmm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kmm.fullname" . }}-prometheus-k8s'
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: '{{ .Release.Namespace }}'