apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kmm.fullname" . }}-service-ca
  labels:
    app.kubernetes.io/component: kmm
    app.kubernetes.io/part-of: kmm
    kmm.openshift.io/ca.type: service
  {{- include "kmm.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}