apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kmm.fullname" . }}-controller
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
