apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-manager
rules:
- apiGroups: ["kmm.sigs.x-k8s.io"]
  resources: ["nodemodulesconfigs", "nodemodulesconfigs/status"]
  verbs: ["get", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "list", "get", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "delete", "create", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "create", "update"]
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
