apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-manager
subjects:
- kind: ServiceAccount
  name: config-manager
roleRef:
  kind: ClusterRole
  name: config-manager
  apiGroup: rbac.authorization.k8s.io