apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-manager
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "list", "get", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "delete", "create", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "create", "update"]
