apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kmm-device-plugin
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmm-device-plugin
subjects:
- kind: ServiceAccount
  name: kmm-device-plugin
