apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-runner
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "list", "get", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch"]
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
