apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: utils-container
subjects:
- kind: ServiceAccount
  name: utils-container
roleRef:
  kind: ClusterRole
  name: utils-container
  apiGroup: rbac.authorization.k8s.io