apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-charts-k8s.fullname" . }}-event-recorder-clusterrolebinding
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm-charts-k8s.fullname" . }}-event-recorder-clusterrole'
subjects:
- kind: ServiceAccount
  name: '{{ include "helm-charts-k8s.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'