apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-k8s.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-gpu-operator-kmm-device-plugin
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmDevicePlugin.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-gpu-operator-kmm-module-loader
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmModuleLoader.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-gpu-operator-node-labeller
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.nodeLabeller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-gpu-operator-metrics-exporter
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metricsExporter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amd-gpu-operator-metrics-exporter-rbac-proxy
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-k8s.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metricsExporter.serviceAccount.annotations | nindent 4 }}
