apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## Append samples you want in your CSV to this file as resources ##
resources:
  - amd.com_deviceconfigs.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
