{{- if .Values.upgradeCRD }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upgrade-crd-hook-sa
  annotations:
    # hook will be executed before helm upgrade
    "helm.sh/hook": pre-upgrade,pre-rollback
    # don't cleanup the job on hook failure
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upgrade-crd-hook-cluster-role
  annotations:
    # hook will be executed before helm upgrade
    "helm.sh/hook": pre-upgrade,pre-rollback
    # don't cleanup the job on hook failure
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: upgrade-crd-hook-cluster-role-binding
  annotations:
    # hook will be executed before helm upgrade
    "helm.sh/hook": pre-upgrade,pre-rollback
    # don't cleanup the job on hook failure
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "2"
subjects:
  - kind: ServiceAccount
    name: upgrade-crd-hook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: upgrade-crd-hook-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-crd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    # hook will be executed before helm upgrade
    "helm.sh/hook": pre-upgrade,pre-rollback
    # don't cleanup the job on hook failure
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: upgrade-crd
    spec:
      serviceAccountName: upgrade-crd-hook-sa
      {{- if .Values.controllerManager.manager.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.controllerManager.manager.imagePullSecrets }}
      {{- end }}
      {{- with .Values.controllerManager.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: upgrade-crd
          image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}
          imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
          command:
          - /bin/sh
          - -c
          - |
            kubectl apply -f /opt/helm-charts-crds-openshift/deviceconfig-crd.yaml
            {{- if .Values.nfd.enabled }}
            kubectl apply -f /opt/helm-charts-crds-openshift/nodefeature-crd.yaml
            kubectl apply -f /opt/helm-charts-crds-openshift/nodefeaturediscovery-crd.yaml
            kubectl apply -f /opt/helm-charts-crds-openshift/nodefeaturerule-crd.yaml
            kubectl apply -f /opt/helm-charts-crds-openshift/noderesourcetopology-crd.yaml
            {{- end }}
            {{- if .Values.kmm.enabled }}
            kubectl apply -f /opt/helm-charts-crds-openshift/module-crd.yaml
            kubectl apply -f /opt/helm-charts-crds-openshift/nodemodulesconfig-crd.yaml
            {{- end }}
      restartPolicy: OnFailure
{{- end }}
# Run helm upgrade with --no-hooks to bypass the pre-upgrade hook