# Run helm uninstall with --no-hooks to bypass the pre-delete hook 
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-uninstall-check-remaining-device-configs
  namespace: {{ .Release.Namespace }}
  annotations:
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "0"
    # hook will be executed before helm uninstall
    "helm.sh/hook": pre-delete
    # remove the resource created by the hook whether it succeeded or failed
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  backoffLimit: 0 # once the job finished first run, don't retry to create another pod
  ttlSecondsAfterFinished: 60 # job info will be kept for 1 min then deleted
  template:
    spec:
      serviceAccountName: {{ include "helm-charts-openshift.fullname" . }}-controller-manager
      containers:
        - name: pre-uninstall-check
          image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}
          command:
            - /bin/sh
            - -c
            - |
              if kubectl get deviceconfigs -n {{ .Release.Namespace }} --no-headers | grep -q .; then
                echo "DeviceConfigs resources exist. Stop uninstallation."
                exit 1
              else
                echo "No DeviceConfigs resources found. Proceeding with uninstallation."
                exit 0
              fi
      {{- if .Values.controllerManager.manager.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.controllerManager.manager.imagePullSecrets }}
      {{- end}}
      restartPolicy: Never

---

# Run helm uninstall with --no-hooks to bypass the pre-delete hook 
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-uninstall-remove-nodefeaturediscovery
  namespace: {{ .Release.Namespace }}
  annotations:
    # hook with lower weight value will run firstly
    "helm.sh/hook-weight": "1"
    # hook will be executed before helm uninstall
    "helm.sh/hook": pre-delete
    # remove the resource created by the hook whether it succeeded or failed
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  backoffLimit: 0 # once the job finished first run, don't retry to create another pod
  ttlSecondsAfterFinished: 60 # job info will be kept for 1 min then deleted
  template:
    spec:
      serviceAccountName: {{ include "helm-charts-openshift.fullname" . }}-controller-manager
      containers:
        - name: pre-uninstall-check
          image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete nodefeaturediscoveries --all -n {{ .Release.Namespace }}
      {{- if .Values.controllerManager.manager.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.controllerManager.manager.imagePullSecrets }}
      {{- end}}
      restartPolicy: Never