# deviceconfig.yaml
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: gpu-operator
  namespace: kube-amd-gpu
spec:
  selector:
    feature.node.kubernetes.io/amd-gpu: "true"

  metricsExporter:
    enable: true
    serviceType: ClusterIP
    image: "docker.io/rocm/device-metrics-exporter:latest"

    rbacConfig:
      enable: true
      secret:
        name: server-metrics-tls
      clientCAConfigMap:
        name: client-ca

    prometheus:
      serviceMonitor:
        enable: true
        interval: 60s
        honorLabels: true
        labels:
          "example": "prom-mtls"
        attachMetadata:
          node: true
        tlsConfig:
          # Prometheus Operator needs permissions to read secrets/configmaps across namespaces.
          # Ensure it has the necessary RBAC or configure it to allow cross-namespace access.
          ca:
            configMap:
              key: ca.crt
              name: prom-server-ca
          cert:
            secret:
              key: client.crt
              name: prom-client-cert
          keySecret:
            key: client.key
            name: prom-client-cert
          serverName: my-metrics-service # Must match the CN or SAN in the server certificate
          insecureSkipVerify: false