controllerManager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=6
    - --tls-cert-file=/etc/secrets/tls.crt
    - --tls-private-key-file=/etc/secrets/tls.key
    - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    containerSecurityContext:
      readOnlyRootFilesystem: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
  manager:
    args:
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    env:
      nodeFeatureDiscoveryImage: quay.io/openshift/origin-node-feature-discovery:4.16
      operatorName: cluster-nfd-operator
      sslCertDir: /etc/pki/tls/certs
    image:
      repository: quay.io/openshift/origin-cluster-nfd-operator
      tag: "4.16"
  replicas: 1
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml: |-
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 39f5e5c3.nodefeaturediscoveries.nfd.openshift.io
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
operator:
  serviceAccount:
    annotations: {}
