apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfd.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "nfd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "nfd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "nfd.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.kubeRbacProxy.args | nindent 8 }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.kubeRbacProxy.image.repository }}:{{ .Values.controllerManager.kubeRbacProxy.image.tag
          | default .Chart.AppVersion }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources: {{- toYaml .Values.controllerManager.kubeRbacProxy.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.controllerManager.kubeRbacProxy.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/secrets
          name: node-feature-discovery-operator-tls
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /node-feature-discovery-operator
        env:
        - name: SSL_CERT_DIR
          value: {{ quote .Values.controllerManager.manager.env.sslCertDir }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ quote .Values.controllerManager.manager.env.operatorName }}
        - name: NODE_FEATURE_DISCOVERY_IMAGE
          value: {{ quote .Values.controllerManager.manager.env.nodeFeatureDiscoveryImage
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      serviceAccountName: {{ include "nfd.fullname" . }}-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: node-feature-discovery-operator-tls
        secret:
          secretName: node-feature-discovery-operator-tls