apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nfd.fullname" . }}-operator
  labels:
  {{- include "nfd.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operator.serviceAccount.annotations | nindent 4 }}